#include"vsip.h"
#undef vsip_acos_d
vsip_scalar_d vsip_acos_d(vsip_scalar_d);
#undef vsip_acos_f
vsip_scalar_f vsip_acos_f(vsip_scalar_f);
#undef vsip_asin_d
vsip_scalar_d vsip_asin_d(vsip_scalar_d);
#undef vsip_asin_f
vsip_scalar_f vsip_asin_f(vsip_scalar_f);
#undef vsip_atan_d
vsip_scalar_d vsip_atan_d(vsip_scalar_d);
#undef vsip_atan_f
vsip_scalar_f vsip_atan_f(vsip_scalar_f);
#undef vsip_ceil_d
vsip_scalar_d vsip_ceil_d(vsip_scalar_d);
#undef vsip_ceil_f
vsip_scalar_f vsip_ceil_f(vsip_scalar_f);
#undef vsip_cos_d
vsip_scalar_d vsip_cos_d(vsip_scalar_d);
#undef vsip_cos_f
vsip_scalar_f vsip_cos_f(vsip_scalar_f);
#undef vsip_cosh_d
vsip_scalar_d vsip_cosh_d(vsip_scalar_d);
#undef vsip_cosh_f
vsip_scalar_f vsip_cosh_f(vsip_scalar_f);
#undef vsip_sin_d
vsip_scalar_d vsip_sin_d(vsip_scalar_d);
#undef vsip_sin_f
vsip_scalar_f vsip_sin_f(vsip_scalar_f);
#undef vsip_sinh_d
vsip_scalar_d vsip_sinh_d(vsip_scalar_d);
#undef vsip_sinh_f
vsip_scalar_f vsip_sinh_f(vsip_scalar_f);
#undef vsip_atan2_d
vsip_scalar_d vsip_atan2_d(vsip_scalar_d, vsip_scalar_d);
#undef vsip_atan2_f
vsip_scalar_f vsip_atan2_f(vsip_scalar_f, vsip_scalar_f);
#undef vsip_hypot_d
vsip_scalar_d vsip_hypot_d(vsip_scalar_d, vsip_scalar_d);
#undef vsip_hypot_f
vsip_scalar_f vsip_hypot_f(vsip_scalar_f, vsip_scalar_f);
#undef vsip_exp_d
vsip_scalar_d vsip_exp_d(vsip_scalar_d);
#undef vsip_exp_f
vsip_scalar_f vsip_exp_f(vsip_scalar_f);
#undef vsip_floor_d
vsip_scalar_d vsip_floor_d(vsip_scalar_d);
#undef vsip_floor_f
vsip_scalar_f vsip_floor_f(vsip_scalar_f);
#undef vsip_log_d
vsip_scalar_d vsip_log_d(vsip_scalar_d);
#undef vsip_log_f
vsip_scalar_f vsip_log_f(vsip_scalar_f);
#undef vsip_log10_d
vsip_scalar_d vsip_log10_d(vsip_scalar_d);
#undef vsip_log10_f
vsip_scalar_f vsip_log10_f(vsip_scalar_f);
#undef vsip_mag_d
vsip_scalar_d vsip_mag_d(vsip_scalar_d);
#undef vsip_mag_f
vsip_scalar_f vsip_mag_f(vsip_scalar_f);
#undef vsip_pow_d
vsip_scalar_d vsip_pow_d(vsip_scalar_d,vsip_scalar_d);
#undef vsip_pow_f
vsip_scalar_f vsip_pow_f(vsip_scalar_f, vsip_scalar_f);
#undef vsip_sqrt_d
vsip_scalar_d vsip_sqrt_d(vsip_scalar_d);
#undef vsip_sqrt_f
vsip_scalar_f vsip_sqrt_f(vsip_scalar_f);
#undef vsip_tan_d
vsip_scalar_d vsip_tan_d(vsip_scalar_d);
#undef vsip_tan_f
vsip_scalar_f vsip_tan_f(vsip_scalar_f);
#undef vsip_tanh_d
vsip_scalar_d vsip_tanh_d(vsip_scalar_d);
#undef vsip_tanh_f
vsip_scalar_f vsip_tanh_f(vsip_scalar_f);
#undef vsip_exp10_d
vsip_scalar_d vsip_exp10_d(vsip_scalar_d);
#undef vsip_exp10_f
vsip_scalar_f vsip_exp10_f(vsip_scalar_f);
#undef vsip_min_d
vsip_scalar_d vsip_min_d(vsip_scalar_d,vsip_scalar_d);
#undef vsip_min_f
vsip_scalar_f vsip_min_f(vsip_scalar_f,vsip_scalar_f);
#undef vsip_max_d
vsip_scalar_d vsip_max_d(vsip_scalar_d,vsip_scalar_d);
#undef vsip_max_f
vsip_scalar_f vsip_max_f(vsip_scalar_f,vsip_scalar_f);
